# Generated by Django 5.0.4 on 2024-04-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0002_сustomers_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('address', models.TextField(verbose_name='Адрес проживание')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone_numder', models.CharField(max_length=15, verbose_name='Телефон')),
                ('password_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('password_issue_data', models.DateField(verbose_name='Дата получения паспорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытие счёта')),
            ],
        ),
        migrations.DeleteModel(
            name='Сustomers',
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs.customers'),
        ),
    ]
