# Generated by Django 5.0.4 on 2024-04-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0003_account_customers_delete_сustomers_account_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Валюта')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, default=' ', max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Д', 'Дебетовый'), ('К', 'Кредитный'), ('Н', 'Накопительный')], default='Д', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opened_at',
            field=models.DateField(default='2000-01-01', verbose_name='Дата открытие счёта'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='Статус счёта'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
                ('expiration_date', models.DateField(verbose_name='Срок окончание действие карты')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs.customers')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='abs.currencys', verbose_name='Валюта'),
        ),
    ]
