# Generated by Django 5.0.4 on 2024-04-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0004_currencys_account_account_type_account_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opened_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата открытие счёта'),
        ),
    ]
