# Generated by Django 5.0.4 on 2024-04-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0005_alter_account_opened_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at',
        ),
    ]
