# Generated by Django 5.0.4 on 2024-04-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0006_remove_customers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='abs.customers'),
        ),
    ]
