# Generated by Django 5.0.4 on 2024-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0007_customers_date_of_birth_alter_account_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password_issue_data',
            field=models.DateField(unique=True, verbose_name='Дата получения паспорта'),
        ),
    ]
