# Generated by Django 5.0.4 on 2024-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abs', '0008_alter_customers_password_issue_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('d', 'disactive')], default='active', max_length=20, verbose_name='Статус счёта'),
        ),
    ]
